### ISSUE TITLE
Application crashing for some users with FileNotFoundException or XamlParseException

### ISSUE THREAD

**Issue by rocksdanister** [microsoft/WindowsAppSDK#3105]
### Describe the bug

The application opens fine but crashes when navigating to settings page or opening dialogs.

Exception when opening dialog:
```
2022-11-02 16:24:45.5875|ERROR|Lively.UI.WinUI.App|Microsoft.UI.Xaml.Markup.XamlParseException: XAML parsing failed.
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Microsoft.UI.Xaml.IApplicationStaticsMethods.LoadComponent(IObjectReference _obj, Object component, Uri resourceLocator, ComponentResourceLocation componentResourceLocation)
   at Microsoft.UI.Xaml.Application.LoadComponent(Object component, Uri resourceLocator, ComponentResourceLocation componentResourceLocation)
   at Lively.UI.WinUI.Views.Pages.AddWallpaperView.InitializeComponent() in C:\Users\rocks\Documents\GitHub\lively\src\Lively\Lively.UI.WinUI\obj\x86\Release\net6.0-windows10.0.18362\win10-x86\Views\Pages\AddWallpaperView.g.i.cs:line 43
   at Lively.UI.WinUI.Views.Pages.AddWallpaperView..ctor(AddWallpaperViewModel vm) in C:\Users\rocks\Documents\GitHub\lively\src\Lively\Lively.UI.WinUI\Views\Pages\AddWallpaperView.xaml.cs:line 37
   at Lively.UI.WinUI.MainWindow.AddWallpaperButton_Click(Object sender, RoutedEventArgs e) in C:\Users\rocks\Documents\GitHub\lively\src\Lively\Lively.UI.WinUI\Views\MainWindow.xaml.cs:line 269
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
```

Exception when opening settings:
```
2022-11-02 18:29:24.5425|ERROR|Lively.UI.WinUI.App|System.IO.FileNotFoundException: The specified module could not be found. (0x8007007E)
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Microsoft.UI.Xaml.IFrameworkElementOverridesMethods.MeasureOverride(IObjectReference _obj, Size availableSize)
   at Microsoft.UI.Xaml.FrameworkElement.MeasureOverride(Size availableSize)
   at Microsoft.UI.Xaml.FrameworkElement.Microsoft.UI.Xaml.IFrameworkElementOverrides.MeasureOverride(Size availableSize)
   at ABI.Microsoft.UI.Xaml.IFrameworkElementOverrides.Do_Abi_MeasureOverride_0(IntPtr thisPtr, Size availableSize, Size* result)
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Microsoft.UI.Xaml.IFrameworkElementOverridesMethods.MeasureOverride(IObjectReference _obj, Size availableSize)
   at Microsoft.UI.Xaml.FrameworkElement.MeasureOverride(Size availableSize)
   at Microsoft.UI.Xaml.FrameworkElement.Microsoft.UI.Xaml.IFrameworkElementOverrides.MeasureOverride(Size availableSize)
   at ABI.Microsoft.UI.Xaml.IFrameworkElementOverrides.Do_Abi_MeasureOverride_0(IntPtr thisPtr, Size availableSize, Size* result)
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Microsoft.UI.Xaml.IFrameworkElementOverridesMethods.MeasureOverride(IObjectReference _obj, Size availableSize)
   at Microsoft.UI.Xaml.FrameworkElement.MeasureOverride(Size availableSize)
   at Microsoft.UI.Xaml.FrameworkElement.Microsoft.UI.Xaml.IFrameworkElementOverrides.MeasureOverride(Size availableSize)
   at ABI.Microsoft.UI.Xaml.IFrameworkElementOverrides.Do_Abi_MeasureOverride_0(IntPtr thisPtr, Size availableSize, Size* result)
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Microsoft.UI.Xaml.IFrameworkElementOverridesMethods.MeasureOverride(IObjectReference _obj, Size availableSize)
   at Microsoft.UI.Xaml.FrameworkElement.MeasureOverride(Size availableSize)
   at Microsoft.UI.Xaml.FrameworkElement.Microsoft.UI.Xaml.IFrameworkElementOverrides.MeasureOverride(Size availableSize)
   at ABI.Microsoft.UI.Xaml.IFrameworkElementOverrides.Do_Abi_MeasureOverride_0(IntPtr thisPtr, Size availableSize, Size* result)
```

### Steps to reproduce the bug

Unable to reproduce on my end.

### NuGet package version

1.2.220930.4-preview2

### Packaging type

Unpackaged

### Windows version

Windows 10 Enterprise 10.0.19042

### IDE

Visual Studio 2022

### Additional context

It is an unpackaged C# application with self contained SDK. 
It was crashing with v1.1.5 SDK also but unable to verify exception because unhandled exception events do not fire.

Original issue: https://github.com/rocksdanister/lively/issues/1448

If you need additional information you can ask @v8f directly.

**Comment by rocksdanister** [comment]
Looks like similar issue https://github.com/rocksdanister/lively/issues/1496

**Comment by haonanttt** [comment]
Win2D issue, according to https://github.com/CommunityToolkit/WindowsCommunityToolkit/issues/4815, author upgraded Microsoft.Graphics.Win2D to v1.2 fixed crashes
