### ISSUE TITLE
TypeInitializationException for WinRT.ActivationFactory (E_ACCESSDENIED)

### ISSUE THREAD

**Issue by DominicMaas** [microsoft/WindowsAppSDK#3228]
### Describe the bug

An exception from a deployed application. This is with Windows App SDK 1.2

See https://github.com/musescore/MuseScore/issues/15032

```
Application: Muse.exe
CoreCLR Version: 6.0.922.41905
.NET Version: 6.0.9
Description: The process was terminated due to an unhandled exception.
Exception Info: System.TypeInitializationException: The type initializer for '<Module>' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'WinRT.ActivationFactory`1' threw an exception.
 ---> System.UnauthorizedAccessException: Access is denied. (0x80070005 (E_ACCESSDENIED))
   at WinRT.BaseActivationFactory..ctor(String typeNamespace, String typeFullName)
   at WinRT.ActivationFactory`1..ctor()
   at WinRT.ActivationFactory`1..cctor()
   --- End of inner exception stack trace ---
   at WinRT.ActivationFactory`1.ActivateInstance[I]()
   at Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentInitializeOptions..ctor()
   at Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentManagerCS.AutoInitialize.get_Options() in D:\a\Muse\Muse\Windows\out\nuget\microsoft.windowsappsdk\1.2.221109.1\include\DeploymentManagerAutoInitializer.cs:line 44
   at Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentManagerCS.AutoInitialize.AccessWindowsAppSDK() in D:\a\Muse\Muse\Windows\out\nuget\microsoft.windowsappsdk\1.2.221109.1\include\DeploymentManagerAutoInitializer.cs:line 30
   at .cctor()
   --- End of inner exception stack trace ---
```

### Steps to reproduce the bug

n/a

### NuGet package version

None

### Packaging type

Packaged (MSIX)

### Windows version

Windows 10 version 21H2 (19044, November 2021 Update)

**Comment by DominicMaas** [comment]
I believe this affects Windows 10 users using 1.2.0. Looks like when installing 1.2.1 (even though the app is built against 1.2.0), it fixes the issue, and the application can launch again.

Can't see anything in the 1.2.1 release notes though...

**Comment by DominicMaas** [comment]
Nah I think this is a bigger issue, maybe related to https://github.com/microsoft/WindowsAppSDK/issues/3137

**Comment by pcxbrook** [comment]
I am experiencing this exact error. Windows 10 (Windows 10 Pro for Workstations 22H2). .NET 7.0 / Maui.  The application never appears nor does it ever hit the first line of code in MainProgram.cs, which is MauiAppBuilder oBuilder = MauiApp.CreateBuilder();

It just started for a another member of the team when he was working on the application.  When I build on my machine, the same error occurs.  The code ran last week, now it does not, so something has changed.  We trying to see what changes were made by reviewing source control.  Any ideas of the root cause?

**Comment by shantisharma** [comment]
I am facing similar error with .NET Version 7.0.2
CoreCLR Version: 7.0.222.60605
.NET Version: 7.0.2
Description: The process was terminated due to an unhandled exception.
Exception Info: System.TypeInitializationException: The type initializer for '<Module>' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'WinRT.ActivationFactory`1' threw an exception.
 ---> System.Runtime.InteropServices.COMException (0x80040154): Class not registered (0x80040154 (REGDB_E_CLASSNOTREG))
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at WinRT.BaseActivationFactory..ctor(String typeNamespace, String typeFullName)
   at WinRT.ActivationFactory`1..ctor()
   at WinRT.ActivationFactory`1..cctor()
   --- End of inner exception stack trace ---
   at WinRT.ActivationFactory`1.ActivateInstance[I]()
   at Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentInitializeOptions..ctor()
   at Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentManagerCS.AutoInitialize.get_Options()

**Comment by npbcts** [comment]
@shantisharma 

I have the same issue as you.

The exception is:

```
Unhandled exception. System.TypeInitializationException: The type initializer for 'WinRT.ActivationFactory`1' threw an exception.
 ---> System.Runtime.InteropServices.COMException (0x80040154): ????? (0x80040154 (REGDB_E_CLASSNOTREG))
   at WinRT.BaseActivationFactory..ctor(String typeNamespace, String typeFullName)
   at WinRT.ActivationFactory`1..ctor()
   at WinRT.ActivationFactory`1..cctor()
   --- End of inner exception stack trace ---
   at WinRT.ActivationFactory`1.As(Guid iid)
   at Microsoft.UI.Xaml.Application.Make___objRef_global__Microsoft_UI_Xaml_IApplicationStatics()
   at Microsoft.UI.Xaml.Application.get__objRef_global__Microsoft_UI_Xaml_IApplicationStatics()
   at Microsoft.UI.Xaml.Application.Start(ApplicationInitializationCallback callback)
   at myProject.Program.Main(String[] args) in C:\Users\User\source\repos\myProject\obj\x64\Debug\net6.0-windows10.0.22621.0\App.g.i.cs:line 25

```

The app running environment:

Version: Windows 11 Enterprise Evalutation, 22H2, 22621.1194
Computer: Oracle VM VirtualBox

This is a winui3 project dependencies:

```
<PackageReference Include="CommunityToolkit.Mvvm" Version="8.1.0" />
<PackageReference Include="CommunityToolkit.WinUI.UI.Controls.DataGrid" Version="7.1.2" />
<PackageReference Include="Microsoft.Extensions.Hosting" Version="7.0.0" />
<PackageReference Include="Microsoft.WindowsAppSDK" Version="1.2.230118.102" />
<PackageReference Include="Microsoft.Xaml.Behaviors.WinUI.Managed" Version="2.0.9" />
<PackageReference Include="WinUIEx" Version="2.1.0" />
```

It create based on croe Microsoft.NETCore.App and .NET Desktop Runtime:

```
$ dotnet --list-sdks
7.0.102 [C:\Program Files\dotnet\sdk]

$ dotnet --list-runtimes
Microsoft.NETCore.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

```

This app run successful on windows10(19041), but it can not run on windows 11(22621), i don`t know the reason.

How to fix it?

**Comment by DrusTheAxe** [comment]
> @shantisharma I am facing similar error with .NET Version 7.0.2...

Are you running Win10? One possible reason for this symptom was due to a bug in Windows (one we couldn't workaround in WinAppSDK). A Windows servicing update to correct that just came out or will soon (I don't recall the exact date).

> @pcxbrook I am experiencing this exact error. Windows 10 (Windows 10 Pro for Workstations 22H2). .NET 7.0 / Maui. The application never appears nor does it ever hit the first line of code in MainProgram.cs, which is MauiAppBuilder oBuilder = MauiApp.CreateBuilder();

Sounds like maybe a dupe of the (known issue #3137)[https://github.com/microsoft/WindowsAppSDK/issues/3137#issuecomment-1332851404] Windows 10 needs the servicing update coming in Jan

@sachintaMSFT do you know how one can tell if that update's present on a system?

**Comment by pcxbrook** [comment]
You can get it to hit the first line of code if you run it from your start menu as administrator.  Thereafter, even in Visual Studio 2022, you can debug until it bombs.  The outline of the Window appears, but nothing renders in it.

There was talk that the second Tuesday in February a fix will be included in a Windows update, but we'll see.

Indeed a bad miss by Micorosoft.  I suspect that too many of the developers are using Windows 11 and that is why it was missed.
________________________________

**Comment by voltz5000** [comment]
I too receive similar error on Windows 11 Pro Version	10.0.22631 Build 22631.  It can start up in rider ok but running from debug folder throws this error.

`Application: W.TemplateMessageClient.exe
CoreCLR Version: 8.0.624.26715
.NET Version: 8.0.6
Description: The process was terminated due to an unhandled exception.
Exception Info: System.TypeInitializationException: The type initializer for '<Module>' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'WinRT.ActivationFactory`1' threw an exception.
 ---> System.Runtime.InteropServices.COMException (0x80040154): Class not registered (0x80040154 (REGDB_E_CLASSNOTREG))
   at WinRT.BaseActivationFactory..ctor(String typeNamespace, String typeFullName)
   at WinRT.ActivationFactory`1..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentInitializeOptions..ctor()
   at Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentManagerCS.AutoInitialize.get_Options() in C:\Users\xyz\.nuget\packages\microsoft.windowsappsdk\1.5.240311000\include\DeploymentManagerAutoInitializer.cs:line 44
   at Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentManagerCS.AutoInitialize.AccessWindowsAppSDK() in C:\Users\xyz\.nuget\packages\microsoft.windowsappsdk\1.5.240311000\include\DeploymentManagerAutoInitializer.cs:line 30
   at .cctor()
   --- End of inner exception stack trace ---
`

**Comment by mominshaikhdevs** [comment]
@MikeHillberg @DrusTheAxe has this issue been fixed? | whats the latest update on this?

**Comment by simong-hs** [comment]
I too experience this:
System.Runtime.InteropServices.COMException (0x80040154): Class not registered (0x80040154 (REGDB_E_CLASSNOTREG)) at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode) at WinRT.BaseActivationFactory..ctor

Runs fine from VS2022, but cannot publish or run a windows exe!

**Comment by xenoranger** [comment]
Why is this not fixed? I get it just by creating a new Maui project. 

Win 11 (10.00.22000.0653)
Visual Studio 2022 (17.12.3)
.Net 8.0.111

Tried building in .Net 9 as well. Still an issue.

**Comment by andrew-aladjev** [comment]
I am still experiencing this issue.

> So please open a new issue for your own scenario and attach the details for your project, rather than reopen this issue.

For what reason? The exception is still the same; no changes since the original issue started. You wanted just to report the issue is closed, but it is not closed.

**Comment by ssparach** [comment]
Thank you for following up here. While the exception message appears the same, the underlying codebase has changed significantly since the original report. To ensure we have the right context and can investigate effectively, please open a new issue with details about your current environment and a minimal repro.
We appreciate your understanding and your help in improving WindowsAppSDK.
