### ISSUE TITLE
Exception thrown: 'System.Runtime.InteropServices.COMException' in WinRT.Runtime.dll

### ISSUE THREAD

**Issue by powext** [microsoft/WindowsAppSDK#4201]
### Describe the bug

I can't use `Windows.ApplicationModel.Background.BackgroundTaskRegistration` at all, once i try to use any of its members i get the following exception
```
System.Runtime.InteropServices.COMException
  HResult=0x80070490
  Message=
  Source=WinRT.Runtime
  StackTrace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.Background.IBackgroundTaskRegistrationStaticsMethods.get_AllTasks(IObjectReference _obj)
   at HotTab.MainWindow.RegisterBackgroundTask() in C:\Users\pow\source\repos\HotTab\HotTab\HotTab\MainWindow.xaml.cs:line 30
```

Since its a nearly bootstraped project I'm attaching the small source code

### Steps to reproduce the bug

Call any member of `Windows.ApplicationModel.Background.BackgroundTaskRegistration`, for example:
`var registeredTasks = BackgroundTaskRegistration.AllTasks;`

### NuGet package version

Windows App SDK 1.4.5: 1.4.240211001

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 21H2 (22000)

### IDE

Visual Studio 2022-preview, Visual Studio 2022

### Additional context

[ProjectToReproduce.zip](https://github.com/microsoft/WindowsAppSDK/files/14290923/ProjectToReproduce.zip)

**Comment by ssparach** [comment]
Thank you for raising this issue and contributing to the project!

Support for [BackgroundTaskBuilder](https://learn.microsoft.com/windows/apps/windows-app-sdk/release-notes-archive/stable-channel-1-7#version-170-17250310001:~:text=New%20Background%20Task%20support) was introduced in WindowsAppSDK version 1.7.0. If you're using an earlier version, we recommend updating to the latest release to take advantage of this functionality.

If you run into any new challenges while working with the API, feel free to open a new issue so we can take a closer look.
