### ISSUE TITLE
Create a PSA app with WindowsAPP SDK

### ISSUE THREAD

**Issue by nitish14s** [microsoft/WindowsAppSDK#4304]
### Discussed in https://github.com/microsoft/WindowsAppSDK/discussions/4301

<div type='discussions-op-text'>

<sup>Originally posted by **nitish14s** March 31, 2024</sup>
I am trying to create a PSA app using WindowsAPPSDK (WinUI3). I have created it as a multiinstancing app and updated the Package.AppManifest of the app 
<Extensions>
 <printsupport:Extension Category="windows.printSupportSettingsUI" EntryPoint="$targetentrypoint$"/>
</Extensions>

But when while opening from a IPP enabled printer to open this app on clicking the Printer Preferences, app is crashing with 
System.Runtime.InteropServices.COMException
</div>

## Steps to Reproduce
1. Add the IPP Class driver (Add printer via IPP)
2. Associate the printer to the PSA via regedit by adding a new key "Association" and add a new value to the registry by adding the app details as in the below screenshot
![image](https://github.com/microsoft/WindowsAppSDK/assets/64186652/7fc0c4c4-30c2-4632-a719-4d6809cc8904)
3.Run the package app and click on Preferences button as available in the IPP Class Driver image given below
4. Observe.
5. ComException occurs
6.  Attaching the sample along

[PSASample.zip](https://github.com/microsoft/WindowsAppSDK/files/14832219/PSASample.zip)

## Stacktrace
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Microsoft.UI.Xaml.IApplicationStaticsMethods.LoadComponent(IObjectReference _obj, Object component, Uri resourceLocator)
   at PSASample.App.InitializeComponent() in C:\code\PSASample\PSASample\PSASample\obj\x64\Debug\net6.0-windows10.0.19041.0\App.g.i.cs:line 57
   at PSASample.App..ctor() in C:\code\PSASample\PSASample\PSASample\App.xaml.cs:line 36
   at PSASample.Program.<>c__DisplayClass1_0.<RedirectActivationTo>b__0() in C:\code\PSASample\PSASample\PSASample\Program.cs:line 46
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)

##IPP Class Driver
![image](https://github.com/microsoft/WindowsAppSDK/assets/64186652/b91d5964-3758-4336-bb5b-6725bc70e29a)

**Comment by ssparach** [comment]
Thank you for reporting this issue. Are you still experiencing the problem? If so, could you provide the latest reproduction steps and consider submitting an item via the FeedbackHub as well?

Thank you!
