### ISSUE TITLE
error MSB6003: The specified task executable "MakePri.exe" could not be run. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.Utilities.Internal, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

### ISSUE THREAD

**Issue by HO-COOH** [microsoft/WindowsAppSDK#4778]
### Describe the bug

Almost the same as #4777 , happens occasionally when I update the wasdk nuget to a newer version.

Build log:
```
1>ListViewSelectedIndex-WinUI.vcxproj -> D:\WinUI-Bug\19-ListViewSelectedIndex\x64\Debug\ListViewSelectedIndex-WinUI\ListViewSelectedIndex_WinUI.exe
1>D:\WinUI-Bug\19-ListViewSelectedIndex\packages\Microsoft.WindowsAppSDK.1.6.240923002\build\Microsoft.Build.Msix.Pri.targets(304,5): error MSB6003: The specified task executable "MakePri.exe" could not be run. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.Utilities.Internal, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
1>D:\WinUI-Bug\19-ListViewSelectedIndex\packages\Microsoft.WindowsAppSDK.1.6.240923002\build\Microsoft.Build.Msix.Pri.targets(304,5): error MSB6003: File name: 'Microsoft.VisualStudio.Utilities.Internal, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
1>D:\WinUI-Bug\19-ListViewSelectedIndex\packages\Microsoft.WindowsAppSDK.1.6.240923002\build\Microsoft.Build.Msix.Pri.targets(304,5): error MSB6003:    at Microsoft.VisualStudio.Telemetry.TelemetrySessionInitializer.BuildInitializer(TelemetrySessionSettings telemetrySessionSettings)
1>D:\WinUI-Bug\19-ListViewSelectedIndex\packages\Microsoft.WindowsAppSDK.1.6.240923002\build\Microsoft.Build.Msix.Pri.targets(304,5): error MSB6003:    at Microsoft.VisualStudio.Telemetry.TelemetryService.get_DefaultSession()
1>D:\WinUI-Bug\19-ListViewSelectedIndex\packages\Microsoft.WindowsAppSDK.1.6.240923002\build\Microsoft.Build.Msix.Pri.targets(304,5): error MSB6003:    at Microsoft.Build.Msix.Telemetry.CreateTelemetrySession(String vsTelemetrySession)
1>D:\WinUI-Bug\19-ListViewSelectedIndex\packages\Microsoft.WindowsAppSDK.1.6.240923002\build\Microsoft.Build.Msix.Pri.targets(304,5): error MSB6003:    at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
1>D:\WinUI-Bug\19-ListViewSelectedIndex\packages\Microsoft.WindowsAppSDK.1.6.240923002\build\Microsoft.Build.Msix.Pri.targets(304,5): error MSB6003:    at Microsoft.Build.Msix.TelemetryOperation..ctor(String vsTelemetrySession, String eventNameSuffix)
1>D:\WinUI-Bug\19-ListViewSelectedIndex\packages\Microsoft.WindowsAppSDK.1.6.240923002\build\Microsoft.Build.Msix.Pri.targets(304,5): error MSB6003:    at Microsoft.Build.Msix.Pri.WinAppSdkGenerateProjectPriFile.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands)
1>D:\WinUI-Bug\19-ListViewSelectedIndex\packages\Microsoft.WindowsAppSDK.1.6.240923002\build\Microsoft.Build.Msix.Pri.targets(304,5): error MSB6003:    at Microsoft.Build.Utilities.ToolTask.Execute()
1>D:\WinUI-Bug\19-ListViewSelectedIndex\packages\Microsoft.WindowsAppSDK.1.6.240923002\build\Microsoft.Build.Msix.Pri.targets(304,5): error MSB6003: 
1>D:\WinUI-Bug\19-ListViewSelectedIndex\packages\Microsoft.WindowsAppSDK.1.6.240923002\build\Microsoft.Build.Msix.Pri.targets(304,5): error MSB6003: WRN: Assembly binding logging is turned OFF.
1>D:\WinUI-Bug\19-ListViewSelectedIndex\packages\Microsoft.WindowsAppSDK.1.6.240923002\build\Microsoft.Build.Msix.Pri.targets(304,5): error MSB6003: To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
1>D:\WinUI-Bug\19-ListViewSelectedIndex\packages\Microsoft.WindowsAppSDK.1.6.240923002\build\Microsoft.Build.Msix.Pri.targets(304,5): error MSB6003: Note: There is some performance penalty associated with assembly bind failure logging.
1>D:\WinUI-Bug\19-ListViewSelectedIndex\packages\Microsoft.WindowsAppSDK.1.6.240923002\build\Microsoft.Build.Msix.Pri.targets(304,5): error MSB6003: To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
1>D:\WinUI-Bug\19-ListViewSelectedIndex\packages\Microsoft.WindowsAppSDK.1.6.240923002\build\Microsoft.Build.Msix.Pri.targets(304,5): error MSB6003:
1>Done building project "ListViewSelectedIndex-WinUI.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Build completed at 2:23 and took 01.327 seconds ==========
========== Deploy: 0 succeeded, 0 failed, 0 skipped ==========
========== Deploy completed at 2:23 and took 01.327 seconds ==========
```

### Steps to reproduce the bug

1. Create a packaged winui3 app (C++)
2. Build once.
3. Upgrade the wasdk package to a newer version.
4. Build again.

### Screenshots

![image](https://github.com/user-attachments/assets/f52410cc-b297-4d6d-b8eb-2b8aa0bc869a)

### NuGet package version

Windows App SDK 1.6.1: 1.6.240923002

### Packaging type

Packaged (MSIX)

### IDE

Visual Studio 2022

**Comment by tom-huntington** [comment]
Did you find a fix?

**Comment by LegendaryBlair** [comment]
Hi @HO-COOH, 
For this issue and issue #4777, are you still be able to repro it? If so, can you use msbuild -bl switch (`msbuild MyProject.proj -bl`) to generate a binary log file (`.binlog`) and share it out. For details, visit [this document](https://learn.microsoft.com/en-us/visualstudio/msbuild/obtaining-build-logs-with-msbuild?view=vs-2022#save-a-binary-log). Once `.binlog` file is provided, we can try to figure out what went wrong in the build process.

**Comment by HO-COOH** [comment]
@LegendaryBlair This issue really only happens when launching for debugging in Visual Studio and trust me, it will reproduce. It does NOT seems to reproduce when using `msbuild` in command line. In this screenshot I first build it inside visual studio (after downgrading the wasdk version, but upgrading will also easily reproduces), failed with `makepri.exe`, then run `msbuild` in the developer terminal, and it build successfully.

![Image](https://github.com/user-attachments/assets/5aa8d3dd-c977-4514-b84b-b17a6968cb6f)

**Comment by LegendaryBlair** [comment]
Hi @HO-COOH,
Just want to clarify, did this error happen when you press F5 or when you clicked build on a project? F5 operation could do more things like app deployment.

In case the latter, you can try to collect `.binlog` file following the instructions below:
1. **Install the Project System Tools Extension**: This extension is available for Visual Studio 2017, 2019, and 2022. You can find it in the Visual Studio Marketplace and install it directly from Visual Studio.
> <img width="283" alt="Image" src="https://github.com/user-attachments/assets/28383855-6004-4a9a-aca4-e7b1d496aa86" />

2. **Open the Build Logging Tool Window**: Once the extension is installed, go to `View > Other Windows > Build Logging` to open the Build Logging tool window.

3. **Start Logging Builds**: In the Build Logging tool window, click the `Start logging builds` button. This will start capturing the build logs for any projects you build in Visual Studio.

4. **Build Your Project**: Now, build your project as you normally would by clicking the `Build` button or using the `Build` menu.

5. **Stop Logging and Save the .binlog File**: After the build is complete, go back to the Build Logging tool window and click the `Stop logging builds` button. You will be prompted to save the .binlog file, which contains the detailed build logs.
> <img width="491" alt="Image" src="https://github.com/user-attachments/assets/25997367-04c8-4530-b035-cf7d3c13dbda" />

**Comment by HO-COOH** [comment]
@LegendaryBlair [WASDKBuildRepro_Debug_x64_DesignTimeBuild_2024-12-26T23_35_20.5421073+08_00.zip](https://github.com/user-attachments/files/18253802/WASDKBuildRepro_Debug_x64_DesignTimeBuild_2024-12-26T23_35_20.5421073%2B08_00.zip)

**Comment by LegendaryBlair** [comment]
Hi @HO-COOH 
Today I used [MSBuild Structured Log Viewer](https://msbuildlog.com/) tool to analyze your log. It turned out that this build was successful. 
**I'm wondering if you can share your solution as zip file so that I can repro from my end.**
<img width="908" alt="Image" src="https://github.com/user-attachments/assets/de0dae10-504d-480d-b669-d1034b6422cb" />

**Comment by HO-COOH** [comment]
@LegendaryBlair 
Sorry I might be drunk then, I think I build twice and it logged the success one. 
Here is the corrected one. [WASDKBuildRepro_Debug_x64_Build_2024-12-27T19_45_30.0459603+08_00.zip](https://github.com/user-attachments/files/18260149/WASDKBuildRepro_Debug_x64_Build_2024-12-27T19_45_30.0459603%2B08_00.zip)

**Comment by haonanttt** [comment]
Hi @HO-COOH , could you follow https://github.com/dotnet/maui/wiki/Capturing-Binary-Logs to:
1. set `MSBuild project build log file verbosity` to `Diagnostic`
2. and collect `.binlog` file again

From current binlog you uploaded, we didn't find enough information about why this happens. And also, we didn't repro this issue from our side

**Comment by HO-COOH** [comment]
@haonanttt 

[WASDKBuildRepro_Debug_x64_Build_2025-01-11T12_26_43.3351558+08_00.zip](https://github.com/user-attachments/files/18384233/WASDKBuildRepro_Debug_x64_Build_2025-01-11T12_26_43.3351558%2B08_00.zip)

**Comment by HO-COOH** [comment]
Happened again.
```
11:27:37:471	1>------ Build started: Project: WinUI3Cpp, Configuration: Debug x64 ------
11:27:37:531	1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(2433,5): warning MSB3106: Assembly strong name "C:\Users\Peter\Desktop\WinUI3Cpp\packages\Microsoft.WindowsAppSDK.1.7.250606001\build\native\..\..\lib\uap10.0\Microsoft.Windows.AI.Foundation.winmd" is either a path which could not be found or it is a full assembly name which is badly formed. If it is a full assembly name it may contain characters that need to be escaped with backslash(\). Those characters are Equals(=), Comma(,), Quote("), Apostrophe('), Backslash(\).
11:27:37:847	1>WinUI3Cpp.vcxproj -> C:\Users\Peter\Desktop\WinUI3Cpp\x64\Debug\WinUI3Cpp\WinUI3Cpp.exe
11:27:37:858	1>C:\Users\Peter\Desktop\WinUI3Cpp\packages\Microsoft.WindowsAppSDK.1.7.250606001\build\Microsoft.Build.Msix.Pri.targets(304,5): error MSB6003: The specified task executable "MakePri.exe" could not be run. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.RemoteControl, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
11:27:37:858	1>C:\Users\Peter\Desktop\WinUI3Cpp\packages\Microsoft.WindowsAppSDK.1.7.250606001\build\Microsoft.Build.Msix.Pri.targets(304,5): error MSB6003: File name: 'Microsoft.VisualStudio.RemoteControl, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
11:27:37:858	1>C:\Users\Peter\Desktop\WinUI3Cpp\packages\Microsoft.WindowsAppSDK.1.7.250606001\build\Microsoft.Build.Msix.Pri.targets(304,5): error MSB6003:    at Microsoft.VisualStudio.Telemetry.TelemetryManifestManagerBuilder.Build(TelemetrySession telemetrySession)
11:27:37:858	1>C:\Users\Peter\Desktop\WinUI3Cpp\packages\Microsoft.WindowsAppSDK.1.7.250606001\build\Microsoft.Build.Msix.Pri.targets(304,5): error MSB6003:    at System.Lazy`1.CreateValue()
11:27:37:858	1>C:\Users\Peter\Desktop\WinUI3Cpp\packages\Microsoft.WindowsAppSDK.1.7.250606001\build\Microsoft.Build.Msix.Pri.targets(304,5): error MSB6003: --- End of stack trace from previous location where exception was thrown ---
11:27:37:858	1>C:\Users\Peter\Desktop\WinUI3Cpp\packages\Microsoft.WindowsAppSDK.1.7.250606001\build\Microsoft.Build.Msix.Pri.targets(304,5): error MSB6003:    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
11:27:37:858	1>C:\Users\Peter\Desktop\WinUI3Cpp\packages\Microsoft.WindowsAppSDK.1.7.250606001\build\Microsoft.Build.Msix.Pri.targets(304,5): error MSB6003:    at System.Lazy`1.get_Value()
11:27:37:858	1>C:\Users\Peter\Desktop\WinUI3Cpp\packages\Microsoft.WindowsAppSDK.1.7.250606001\build\Microsoft.Build.Msix.Pri.targets(304,5): error MSB6003:    at Microsoft.VisualStudio.Telemetry.TelemetrySession.InitializeWithDefaultChannels(Boolean checkPendingAsimovEvents)
11:27:37:858	1>C:\Users\Peter\Desktop\WinUI3Cpp\packages\Microsoft.WindowsAppSDK.1.7.250606001\build\Microsoft.Build.Msix.Pri.targets(304,5): error MSB6003:    at Microsoft.VisualStudio.Telemetry.TelemetrySession.Start(Boolean checkPendingAsimovEvents)
11:27:37:858	1>C:\Users\Peter\Desktop\WinUI3Cpp\packages\Microsoft.WindowsAppSDK.1.7.250606001\build\Microsoft.Build.Msix.Pri.targets(304,5): error MSB6003:    at Microsoft.Build.Msix.Telemetry.CreateTelemetrySession(String vsTelemetrySession)
11:27:37:858	1>C:\Users\Peter\Desktop\WinUI3Cpp\packages\Microsoft.WindowsAppSDK.1.7.250606001\build\Microsoft.Build.Msix.Pri.targets(304,5): error MSB6003:    at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
11:27:37:858	1>C:\Users\Peter\Desktop\WinUI3Cpp\packages\Microsoft.WindowsAppSDK.1.7.250606001\build\Microsoft.Build.Msix.Pri.targets(304,5): error MSB6003:    at Microsoft.Build.Msix.TelemetryOperation..ctor(String vsTelemetrySession, String eventNameSuffix)
11:27:37:858	1>C:\Users\Peter\Desktop\WinUI3Cpp\packages\Microsoft.WindowsAppSDK.1.7.250606001\build\Microsoft.Build.Msix.Pri.targets(304,5): error MSB6003:    at Microsoft.Build.Msix.Pri.WinAppSdkGenerateProjectPriFile.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands)
11:27:37:858	1>C:\Users\Peter\Desktop\WinUI3Cpp\packages\Microsoft.WindowsAppSDK.1.7.250606001\build\Microsoft.Build.Msix.Pri.targets(304,5): error MSB6003:    at Microsoft.Build.Utilities.ToolTask.Execute()
11:27:37:858	1>C:\Users\Peter\Desktop\WinUI3Cpp\packages\Microsoft.WindowsAppSDK.1.7.250606001\build\Microsoft.Build.Msix.Pri.targets(304,5): error MSB6003: 
11:27:37:858	1>C:\Users\Peter\Desktop\WinUI3Cpp\packages\Microsoft.WindowsAppSDK.1.7.250606001\build\Microsoft.Build.Msix.Pri.targets(304,5): error MSB6003: WRN: Assembly binding logging is turned OFF.
11:27:37:858	1>C:\Users\Peter\Desktop\WinUI3Cpp\packages\Microsoft.WindowsAppSDK.1.7.250606001\build\Microsoft.Build.Msix.Pri.targets(304,5): error MSB6003: To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
11:27:37:858	1>C:\Users\Peter\Desktop\WinUI3Cpp\packages\Microsoft.WindowsAppSDK.1.7.250606001\build\Microsoft.Build.Msix.Pri.targets(304,5): error MSB6003: Note: There is some performance penalty associated with assembly bind failure logging.
11:27:37:858	1>C:\Users\Peter\Desktop\WinUI3Cpp\packages\Microsoft.WindowsAppSDK.1.7.250606001\build\Microsoft.Build.Msix.Pri.targets(304,5): error MSB6003: To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
11:27:37:858	1>C:\Users\Peter\Desktop\WinUI3Cpp\packages\Microsoft.WindowsAppSDK.1.7.250606001\build\Microsoft.Build.Msix.Pri.targets(304,5): error MSB6003:
11:27:37:858	1>Done building project "WinUI3Cpp.vcxproj" -- FAILED.
11:27:37:864	========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
11:27:37:864	========== Build completed at 11:27 AM and took 00.473 seconds ==========
11:27:37:864	========== Deploy: 0 succeeded, 0 failed, 0 skipped ==========
11:27:37:864	========== Deploy completed at 11:27 AM and took 00.473 seconds ==========

```

**Comment by HO-COOH** [comment]
Still happens with 1.8.2
```
\WinUI3Cpp2\packages\Microsoft.Windows.SDK.BuildTools.MSIX.1.7.20250829.1\build\Microsoft.Windows.SDK.BuildTools.MSIX.Pri.targets(349,5): error MSB6003: The specified task executable "MakePri.exe" could not be run. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.RemoteControl, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. 系统找不到指定的文件。
\WinUI3Cpp2\packages\Microsoft.Windows.SDK.BuildTools.MSIX.1.7.20250829.1\build\Microsoft.Windows.SDK.BuildTools.MSIX.Pri.targets(349,5): error MSB6003: File name: 'Microsoft.VisualStudio.RemoteControl, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
\WinUI3Cpp2\packages\Microsoft.Windows.SDK.BuildTools.MSIX.1.7.20250829.1\build\Microsoft.Windows.SDK.BuildTools.MSIX.Pri.targets(349,5): error MSB6003:    at Microsoft.VisualStudio.Telemetry.TelemetryManifestManagerBuilder.Build(TelemetrySession telemetrySession)
\WinUI3Cpp2\packages\Microsoft.Windows.SDK.BuildTools.MSIX.1.7.20250829.1\build\Microsoft.Windows.SDK.BuildTools.MSIX.Pri.targets(349,5): error MSB6003:    at System.Lazy`1.CreateValue()
\WinUI3Cpp2\packages\Microsoft.Windows.SDK.BuildTools.MSIX.1.7.20250829.1\build\Microsoft.Windows.SDK.BuildTools.MSIX.Pri.targets(349,5): error MSB6003:    at System.Lazy`1.LazyInitValue()
\WinUI3Cpp2\packages\Microsoft.Windows.SDK.BuildTools.MSIX.1.7.20250829.1\build\Microsoft.Windows.SDK.BuildTools.MSIX.Pri.targets(349,5): error MSB6003:    at Microsoft.VisualStudio.Telemetry.TelemetrySessionInternalBase.InitializeWithDefaultChannels(Boolean checkPendingAsimovEvents)
\WinUI3Cpp2\packages\Microsoft.Windows.SDK.BuildTools.MSIX.1.7.20250829.1\build\Microsoft.Windows.SDK.BuildTools.MSIX.Pri.targets(349,5): error MSB6003:    at Microsoft.VisualStudio.Telemetry.TelemetrySessionInternalBase.Start(Boolean checkPendingAsimovEvents)
\WinUI3Cpp2\packages\Microsoft.Windows.SDK.BuildTools.MSIX.1.7.20250829.1\build\Microsoft.Windows.SDK.BuildTools.MSIX.Pri.targets(349,5): error MSB6003:    at Microsoft.Build.Msix.Telemetry.CreateTelemetrySession(String vsTelemetrySession)
\WinUI3Cpp2\packages\Microsoft.Windows.SDK.BuildTools.MSIX.1.7.20250829.1\build\Microsoft.Windows.SDK.BuildTools.MSIX.Pri.targets(349,5): error MSB6003:    at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
\WinUI3Cpp2\packages\Microsoft.Windows.SDK.BuildTools.MSIX.1.7.20250829.1\build\Microsoft.Windows.SDK.BuildTools.MSIX.Pri.targets(349,5): error MSB6003:    at Microsoft.Build.Msix.TelemetryOperation..ctor(String vsTelemetrySession, String eventNameSuffix)
\WinUI3Cpp2\packages\Microsoft.Windows.SDK.BuildTools.MSIX.1.7.20250829.1\build\Microsoft.Windows.SDK.BuildTools.MSIX.Pri.targets(349,5): error MSB6003:    at Microsoft.Build.Msix.Pri.WinAppSdkGenerateProjectPriFile.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands)
\WinUI3Cpp2\packages\Microsoft.Windows.SDK.BuildTools.MSIX.1.7.20250829.1\build\Microsoft.Windows.SDK.BuildTools.MSIX.Pri.targets(349,5): error MSB6003:    at Microsoft.Build.Utilities.ToolTask.Execute()
\WinUI3Cpp2\packages\Microsoft.Windows.SDK.BuildTools.MSIX.1.7.20250829.1\build\Microsoft.Windows.SDK.BuildTools.MSIX.Pri.targets(349,5): error MSB6003: 
\WinUI3Cpp2\packages\Microsoft.Windows.SDK.BuildTools.MSIX.1.7.20250829.1\build\Microsoft.Windows.SDK.BuildTools.MSIX.Pri.targets(349,5): error MSB6003: WRN: Assembly binding logging is turned OFF.
\WinUI3Cpp2\packages\Microsoft.Windows.SDK.BuildTools.MSIX.1.7.20250829.1\build\Microsoft.Windows.SDK.BuildTools.MSIX.Pri.targets(349,5): error MSB6003: To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
\WinUI3Cpp2\packages\Microsoft.Windows.SDK.BuildTools.MSIX.1.7.20250829.1\build\Microsoft.Windows.SDK.BuildTools.MSIX.Pri.targets(349,5): error MSB6003: Note: There is some performance penalty associated with assembly bind failure logging.
\WinUI3Cpp2\packages\Microsoft.Windows.SDK.BuildTools.MSIX.1.7.20250829.1\build\Microsoft.Windows.SDK.BuildTools.MSIX.Pri.targets(349,5): error MSB6003: To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
\WinUI3Cpp2\packages\Microsoft.Windows.SDK.BuildTools.MSIX.1.7.20250829.1\build\Microsoft.Windows.SDK.BuildTools.MSIX.Pri.targets(349,5): error MSB6003:
```
