### ISSUE TITLE
VSIX Installer installation failed 

### ISSUE THREAD

**Issue by akhterm** [microsoft/WindowsAppSDK#698]
**Describe the bug**
VSIX Installer Modification failed, 

VS 2019 Enterprise version: 16.9.2

Please find the logs here with for reference 

````
4/6/2021 2:51:15 PM - Microsoft VSIX Installer
4/6/2021 2:51:15 PM - -------------------------------------------
4/6/2021 2:51:15 PM - vsixinstaller.exe version:
4/6/2021 2:51:15 PM - 16.10.10
4/6/2021 2:51:15 PM - -------------------------------------------
4/6/2021 2:51:15 PM - Command line parameters:
4/6/2021 2:51:15 PM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\vsixinstaller.exe,/appidinstallpath:C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\devenv.exe,/skuName:Enterprise,/skuVersion:16.9.31112.23,/appidname:Microsoft Visual Studio Enterprise 2019,/culture:en-US,/noep,C:\Users\m.akhter\AppData\Local\Temp\VSIXsgj0zmzh.vsix,/callingprocessid:11824,/installas:3508
4/6/2021 2:51:15 PM - -------------------------------------------
4/6/2021 2:51:15 PM - Microsoft VSIX Installer
4/6/2021 2:51:15 PM - -------------------------------------------
4/6/2021 2:51:17 PM - Initializing Install...
4/6/2021 2:51:17 PM - Extension Details...
4/6/2021 2:51:17 PM - 	Identifier         : Microsoft.ProjectReunion
4/6/2021 2:51:17 PM - 	Name               : Project Reunion
4/6/2021 2:51:17 PM - 	Author             : Microsoft
4/6/2021 2:51:17 PM - 	Version            : 0.5.0.85112000
4/6/2021 2:51:17 PM - 	Description        : The Microsoft Project Reunion Visual Studio extension adds project and item templates to support building Windows apps and components.
4/6/2021 2:51:17 PM - 	Locale             : en-US
4/6/2021 2:51:17 PM - 	MoreInfoURL        : https://github.com/microsoft/ProjectReunion/
4/6/2021 2:51:17 PM - 	InstalledByMSI     : False
4/6/2021 2:51:17 PM - 	SupportedFrameworkVersionRange : [4.5,)
4/6/2021 2:51:17 PM - 
4/6/2021 2:51:18 PM - 	SignatureState     : ValidSignature
4/6/2021 2:51:18 PM - 	SignedBy           : Microsoft Corporation
4/6/2021 2:51:18 PM - 	Certificate Info   : 
4/6/2021 2:51:18 PM - 		-------------------------------------------------------
4/6/2021 2:51:18 PM - 		[Subject]       : CN=Microsoft Corporation, OU=OPC, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
4/6/2021 2:51:18 PM - 		[Issuer]        : CN=Microsoft Code Signing PCA 2010, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
4/6/2021 2:51:18 PM - 		[Serial Number] : 33000003C93EFB7FE21A3D22B30000000003C9
4/6/2021 2:51:18 PM - 		[Not Before]    : 12/16/2020 1:24:05 AM
4/6/2021 2:51:18 PM - 		[Not After]     : 12/3/2021 1:24:05 AM
4/6/2021 2:51:18 PM - 		[Thumbprint]    : E120FF932F2D4DFB59B1DA16BA7C397119E2DEBF
4/6/2021 2:51:18 PM - 
4/6/2021 2:51:18 PM - 	Supported Products : 
4/6/2021 2:51:18 PM - 		Microsoft.VisualStudio.Community
4/6/2021 2:51:18 PM - 			Version : [16.9,17.0)
4/6/2021 2:51:18 PM - 		Microsoft.VisualStudio.Pro
4/6/2021 2:51:18 PM - 			Version : [16.9,17.0)
4/6/2021 2:51:18 PM - 		Microsoft.VisualStudio.Enterprise
4/6/2021 2:51:18 PM - 			Version : [16.9,17.0)
4/6/2021 2:51:18 PM - 
4/6/2021 2:51:18 PM - 	References         : 
4/6/2021 2:51:18 PM - 	Prerequisites      : 
4/6/2021 2:51:18 PM - 		-------------------------------------------------------
4/6/2021 2:51:18 PM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
4/6/2021 2:51:18 PM - 		Name         : Visual Studio core editor
4/6/2021 2:51:18 PM - 		Version      : [16.0,17.0)
4/6/2021 2:51:18 PM - 
4/6/2021 2:51:18 PM - 		-------------------------------------------------------
4/6/2021 2:51:18 PM - 		Identifier   : Microsoft.VisualStudio.ComponentGroup.UWP.Support
4/6/2021 2:51:18 PM - 		Name         : Universal Windows Platform tools
4/6/2021 2:51:18 PM - 		Version      : [16.2.29003.222,17.0)
4/6/2021 2:51:18 PM - 
4/6/2021 2:51:18 PM - Signature Details...
4/6/2021 2:51:18 PM - 	Extension is signed with a valid signature.

4/6/2021 2:51:32 PM - Skipping cache of package 'Component.Xamarin.Profiler,version=16.0.28315.86' since the package or a parent package had a vital failure.
4/6/2021 2:51:32 PM - Skipping Install of 'Microsoft.ProjectReunion,version=0.5.0.85112000' since the package or a parent package had a vital failure.
4/6/2021 2:51:32 PM - Skipping cache of package 'Microsoft.ProjectReunion,version=0.5.0.85112000' since the package or a parent package had a vital failure.
4/6/2021 2:51:32 PM - Skipping cache of package 'Component.Microsoft.ProjectReunion,version=0.5.0.85112000' since the package or a parent package had a vital failure.
4/6/2021 2:51:56 PM - Install Error : System.AggregateException: One or more errors occurred. ---> Microsoft.VisualStudio.Setup.PackageFailureException: Package 'Microsoft.VisualCpp.CRT.ClickOnce.Msi' failed to install
   at Microsoft.VisualStudio.Setup.InstallOperation.Run(CancellationToken token)
   at Microsoft.VisualStudio.Setup.Engine.RunOperation(InstallOperation installOperation, CancellationToken token, ExecuteAction action, ITelemetryOperation telemetryOperation)
   at Microsoft.VisualStudio.Setup.Engine.RunCoreOperation(InstallOperation coreOperation, ExecuteAction action, ITelemetryOperation telemetryOperation, CancellationToken token)
   at Microsoft.VisualStudio.Setup.Engine.Install(Product product, String destination, CancellationToken token)
   at Microsoft.VisualStudio.ExtensionManager.SetupEngineService.<Install>b__14_0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ExtensionManager.SetupEngineService.Install()
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformSetupEngineInstall(InstallableExtensionImpl extension, Boolean installPerMachine, Boolean isPackComponent, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, IProgress`1 progress, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion, IInstalledExtension& newExtension)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallInternal(InstallableExtensionImpl extension, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress, Version targetedVsVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.BeginInstall(IInstallableExtension installableExtension, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallWorker(IInstallableExtension extension, InstallFlags installFlags, AsyncOperation asyncOp)
---> (Inner Exception #0) Microsoft.VisualStudio.Setup.PackageFailureException: Package 'Microsoft.VisualCpp.CRT.ClickOnce.Msi' failed to install
   at Microsoft.VisualStudio.Setup.InstallOperation.Run(CancellationToken token)
   at Microsoft.VisualStudio.Setup.Engine.RunOperation(InstallOperation installOperation, CancellationToken token, ExecuteAction action, ITelemetryOperation telemetryOperation)
   at Microsoft.VisualStudio.Setup.Engine.RunCoreOperation(InstallOperation coreOperation, ExecuteAction action, ITelemetryOperation telemetryOperation, CancellationToken token)
   at Microsoft.VisualStudio.Setup.Engine.Install(Product product, String destination, CancellationToken token)
   at Microsoft.VisualStudio.ExtensionManager.SetupEngineService.<Install>b__14_0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

```

Kindly advise how to fix it
`

**Comment by BenJKuhn** [comment]
@akhterm, just for our triage / investigation, can you clarify: are you an admin on the machine, or running as a standard user?

**Comment by akhterm** [comment]
Am admin user

**Comment by akhterm** [comment]
any updates!

**Comment by DefaultRyan** [comment]
I believe this has been fixed. Feel free to reopen if you are still seeing this issue.
